export const GET_MODULE_INFO_START = 'GET_MODULE_INFO_START'
export const GET_MODULE_INFO_SUCCESS = 'GET_MODULE_INFO_SUCCESS'
export const GET_MODULE_INFO_FAIL = 'GET_MODULE_INFO_FAIL'

export const GET_SEARCH_INFO_SUCCESS = 'GET_SEARCH_INFO_SUCCESS'


export const GET_DATE_INFO_SUCCESS = 'GET_DATE_INFO_SUCCESS'    //获取日期
export const GET_DATE_MINPRICE_SUCCESS = 'GET_DATE_MINPRICE_SUCCESS'      //获取当前选中日期最小价格   

export const GET_INSURANCE_INFO_SUCCESS = 'GET_INSURANCE_INFO_SUCCESS'
export const GET_CHOSED_INSURANCE_SUCCESS = 'GET_CHOSED_INSURANCE_SUCCESS'

export const GET_TRAIN_INSURANCE_INFO_SUCCESS = 'GET_TRAIN_INSURANCE_INFO_SUCCESS'
export const GET_CHOSED_TRAIN_INSURANCE_SUCCESS = 'GET_CHOSED_TRAIN_INSURANCE_SUCCESS'

export const GET_EXPENSE_DETAIL_SUCCESS = 'GET_EXPENSE_DETAIL_SUCCESS'   //获取费用明细

export const GET_ONEWAY_FLIGHT_LIST_START = 'GET_ONEWAY_FLIGHT_LIST_START'     //单程机票因公因私列表请求中
export const GET_ONEWAY_FLIGHT_LIST_SUCCESS = 'GET_ONEWAY_FLIGHT_LIST_SUCCESS'     //单程机票因公因私列表请求完成
export const GET_ONEWAY_FLIGHT_LIST_FAILE = 'GET_ONEWAY_FLIGHT_LIST_FAILE'     //单程机票因公因私列表请求失败

export const SORT_FLIGHT_LIST_SUCCESS = 'SORT_FLIGHT_LIST_SUCCESS'     //列表排序
export const FILTER_FLIGHT_LIST_SUCCESS = 'FILTER_FLIGHT_LIST_SUCCESS'     //列表筛选

export const GET_TRAIN_LIST_START = 'GET_TRAIN_LIST_STAR'     //火车列表请求中
export const GET_TRAIN_LIST_SUCCESS = 'GET_TRAIN_LIST_SUCCESS'     //火车列表请求完成
export const GET_TRAIN_LIST_FAILE = 'GET_TRAIN_LIST_FAILE'     //火车列表请求失败

export const GET_FREQUENT_PSGER = 'GET_FREQUENT_PSGER'          //获取常旅客